// Code generated by ent, DO NOT EDIT.

package proxy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldName, v))
}

// ExternalKey applies equality check predicate on the "external_key" field. It's identical to ExternalKeyEQ.
func ExternalKey(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExternalKey, v))
}

// Protocol applies equality check predicate on the "protocol" field. It's identical to ProtocolEQ.
func Protocol(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldProtocol, v))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldHost, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPort, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUsername, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPassword, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldStatus, v))
}

// NetworkStatus applies equality check predicate on the "network_status" field. It's identical to NetworkStatusEQ.
func NetworkStatus(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldNetworkStatus, v))
}

// NetworkCheckedAt applies equality check predicate on the "network_checked_at" field. It's identical to NetworkCheckedAtEQ.
func NetworkCheckedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldNetworkCheckedAt, v))
}

// NetworkErrorMessage applies equality check predicate on the "network_error_message" field. It's identical to NetworkErrorMessageEQ.
func NetworkErrorMessage(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldNetworkErrorMessage, v))
}

// ExitIP applies equality check predicate on the "exit_ip" field. It's identical to ExitIPEQ.
func ExitIP(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitIP, v))
}

// ExitIPCheckedAt applies equality check predicate on the "exit_ip_checked_at" field. It's identical to ExitIPCheckedAtEQ.
func ExitIPCheckedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitIPCheckedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldName, v))
}

// ExternalKeyEQ applies the EQ predicate on the "external_key" field.
func ExternalKeyEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExternalKey, v))
}

// ExternalKeyNEQ applies the NEQ predicate on the "external_key" field.
func ExternalKeyNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExternalKey, v))
}

// ExternalKeyIn applies the In predicate on the "external_key" field.
func ExternalKeyIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExternalKey, vs...))
}

// ExternalKeyNotIn applies the NotIn predicate on the "external_key" field.
func ExternalKeyNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExternalKey, vs...))
}

// ExternalKeyGT applies the GT predicate on the "external_key" field.
func ExternalKeyGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExternalKey, v))
}

// ExternalKeyGTE applies the GTE predicate on the "external_key" field.
func ExternalKeyGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExternalKey, v))
}

// ExternalKeyLT applies the LT predicate on the "external_key" field.
func ExternalKeyLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExternalKey, v))
}

// ExternalKeyLTE applies the LTE predicate on the "external_key" field.
func ExternalKeyLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExternalKey, v))
}

// ExternalKeyContains applies the Contains predicate on the "external_key" field.
func ExternalKeyContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldExternalKey, v))
}

// ExternalKeyHasPrefix applies the HasPrefix predicate on the "external_key" field.
func ExternalKeyHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldExternalKey, v))
}

// ExternalKeyHasSuffix applies the HasSuffix predicate on the "external_key" field.
func ExternalKeyHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldExternalKey, v))
}

// ExternalKeyIsNil applies the IsNil predicate on the "external_key" field.
func ExternalKeyIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExternalKey))
}

// ExternalKeyNotNil applies the NotNil predicate on the "external_key" field.
func ExternalKeyNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExternalKey))
}

// ExternalKeyEqualFold applies the EqualFold predicate on the "external_key" field.
func ExternalKeyEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldExternalKey, v))
}

// ExternalKeyContainsFold applies the ContainsFold predicate on the "external_key" field.
func ExternalKeyContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldExternalKey, v))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldProtocol, vs...))
}

// ProtocolGT applies the GT predicate on the "protocol" field.
func ProtocolGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldProtocol, v))
}

// ProtocolGTE applies the GTE predicate on the "protocol" field.
func ProtocolGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldProtocol, v))
}

// ProtocolLT applies the LT predicate on the "protocol" field.
func ProtocolLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldProtocol, v))
}

// ProtocolLTE applies the LTE predicate on the "protocol" field.
func ProtocolLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldProtocol, v))
}

// ProtocolContains applies the Contains predicate on the "protocol" field.
func ProtocolContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldProtocol, v))
}

// ProtocolHasPrefix applies the HasPrefix predicate on the "protocol" field.
func ProtocolHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldProtocol, v))
}

// ProtocolHasSuffix applies the HasSuffix predicate on the "protocol" field.
func ProtocolHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldProtocol, v))
}

// ProtocolEqualFold applies the EqualFold predicate on the "protocol" field.
func ProtocolEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldProtocol, v))
}

// ProtocolContainsFold applies the ContainsFold predicate on the "protocol" field.
func ProtocolContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldProtocol, v))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldHost, v))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldHost, v))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldPort, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameIsNil applies the IsNil predicate on the "username" field.
func UsernameIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldUsername))
}

// UsernameNotNil applies the NotNil predicate on the "username" field.
func UsernameNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldUsername))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldUsername, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordIsNil applies the IsNil predicate on the "password" field.
func PasswordIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldPassword))
}

// PasswordNotNil applies the NotNil predicate on the "password" field.
func PasswordNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldPassword))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldPassword, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldStatus, v))
}

// NetworkStatusEQ applies the EQ predicate on the "network_status" field.
func NetworkStatusEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldNetworkStatus, v))
}

// NetworkStatusNEQ applies the NEQ predicate on the "network_status" field.
func NetworkStatusNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldNetworkStatus, v))
}

// NetworkStatusIn applies the In predicate on the "network_status" field.
func NetworkStatusIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldNetworkStatus, vs...))
}

// NetworkStatusNotIn applies the NotIn predicate on the "network_status" field.
func NetworkStatusNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldNetworkStatus, vs...))
}

// NetworkStatusGT applies the GT predicate on the "network_status" field.
func NetworkStatusGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldNetworkStatus, v))
}

// NetworkStatusGTE applies the GTE predicate on the "network_status" field.
func NetworkStatusGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldNetworkStatus, v))
}

// NetworkStatusLT applies the LT predicate on the "network_status" field.
func NetworkStatusLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldNetworkStatus, v))
}

// NetworkStatusLTE applies the LTE predicate on the "network_status" field.
func NetworkStatusLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldNetworkStatus, v))
}

// NetworkStatusContains applies the Contains predicate on the "network_status" field.
func NetworkStatusContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldNetworkStatus, v))
}

// NetworkStatusHasPrefix applies the HasPrefix predicate on the "network_status" field.
func NetworkStatusHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldNetworkStatus, v))
}

// NetworkStatusHasSuffix applies the HasSuffix predicate on the "network_status" field.
func NetworkStatusHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldNetworkStatus, v))
}

// NetworkStatusIsNil applies the IsNil predicate on the "network_status" field.
func NetworkStatusIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldNetworkStatus))
}

// NetworkStatusNotNil applies the NotNil predicate on the "network_status" field.
func NetworkStatusNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldNetworkStatus))
}

// NetworkStatusEqualFold applies the EqualFold predicate on the "network_status" field.
func NetworkStatusEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldNetworkStatus, v))
}

// NetworkStatusContainsFold applies the ContainsFold predicate on the "network_status" field.
func NetworkStatusContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldNetworkStatus, v))
}

// NetworkCheckedAtEQ applies the EQ predicate on the "network_checked_at" field.
func NetworkCheckedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldNetworkCheckedAt, v))
}

// NetworkCheckedAtNEQ applies the NEQ predicate on the "network_checked_at" field.
func NetworkCheckedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldNetworkCheckedAt, v))
}

// NetworkCheckedAtIn applies the In predicate on the "network_checked_at" field.
func NetworkCheckedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldNetworkCheckedAt, vs...))
}

// NetworkCheckedAtNotIn applies the NotIn predicate on the "network_checked_at" field.
func NetworkCheckedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldNetworkCheckedAt, vs...))
}

// NetworkCheckedAtGT applies the GT predicate on the "network_checked_at" field.
func NetworkCheckedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldNetworkCheckedAt, v))
}

// NetworkCheckedAtGTE applies the GTE predicate on the "network_checked_at" field.
func NetworkCheckedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldNetworkCheckedAt, v))
}

// NetworkCheckedAtLT applies the LT predicate on the "network_checked_at" field.
func NetworkCheckedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldNetworkCheckedAt, v))
}

// NetworkCheckedAtLTE applies the LTE predicate on the "network_checked_at" field.
func NetworkCheckedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldNetworkCheckedAt, v))
}

// NetworkCheckedAtIsNil applies the IsNil predicate on the "network_checked_at" field.
func NetworkCheckedAtIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldNetworkCheckedAt))
}

// NetworkCheckedAtNotNil applies the NotNil predicate on the "network_checked_at" field.
func NetworkCheckedAtNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldNetworkCheckedAt))
}

// NetworkErrorMessageEQ applies the EQ predicate on the "network_error_message" field.
func NetworkErrorMessageEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldNetworkErrorMessage, v))
}

// NetworkErrorMessageNEQ applies the NEQ predicate on the "network_error_message" field.
func NetworkErrorMessageNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldNetworkErrorMessage, v))
}

// NetworkErrorMessageIn applies the In predicate on the "network_error_message" field.
func NetworkErrorMessageIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldNetworkErrorMessage, vs...))
}

// NetworkErrorMessageNotIn applies the NotIn predicate on the "network_error_message" field.
func NetworkErrorMessageNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldNetworkErrorMessage, vs...))
}

// NetworkErrorMessageGT applies the GT predicate on the "network_error_message" field.
func NetworkErrorMessageGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldNetworkErrorMessage, v))
}

// NetworkErrorMessageGTE applies the GTE predicate on the "network_error_message" field.
func NetworkErrorMessageGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldNetworkErrorMessage, v))
}

// NetworkErrorMessageLT applies the LT predicate on the "network_error_message" field.
func NetworkErrorMessageLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldNetworkErrorMessage, v))
}

// NetworkErrorMessageLTE applies the LTE predicate on the "network_error_message" field.
func NetworkErrorMessageLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldNetworkErrorMessage, v))
}

// NetworkErrorMessageContains applies the Contains predicate on the "network_error_message" field.
func NetworkErrorMessageContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldNetworkErrorMessage, v))
}

// NetworkErrorMessageHasPrefix applies the HasPrefix predicate on the "network_error_message" field.
func NetworkErrorMessageHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldNetworkErrorMessage, v))
}

// NetworkErrorMessageHasSuffix applies the HasSuffix predicate on the "network_error_message" field.
func NetworkErrorMessageHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldNetworkErrorMessage, v))
}

// NetworkErrorMessageIsNil applies the IsNil predicate on the "network_error_message" field.
func NetworkErrorMessageIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldNetworkErrorMessage))
}

// NetworkErrorMessageNotNil applies the NotNil predicate on the "network_error_message" field.
func NetworkErrorMessageNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldNetworkErrorMessage))
}

// NetworkErrorMessageEqualFold applies the EqualFold predicate on the "network_error_message" field.
func NetworkErrorMessageEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldNetworkErrorMessage, v))
}

// NetworkErrorMessageContainsFold applies the ContainsFold predicate on the "network_error_message" field.
func NetworkErrorMessageContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldNetworkErrorMessage, v))
}

// ExitIPEQ applies the EQ predicate on the "exit_ip" field.
func ExitIPEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitIP, v))
}

// ExitIPNEQ applies the NEQ predicate on the "exit_ip" field.
func ExitIPNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExitIP, v))
}

// ExitIPIn applies the In predicate on the "exit_ip" field.
func ExitIPIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExitIP, vs...))
}

// ExitIPNotIn applies the NotIn predicate on the "exit_ip" field.
func ExitIPNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExitIP, vs...))
}

// ExitIPGT applies the GT predicate on the "exit_ip" field.
func ExitIPGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExitIP, v))
}

// ExitIPGTE applies the GTE predicate on the "exit_ip" field.
func ExitIPGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExitIP, v))
}

// ExitIPLT applies the LT predicate on the "exit_ip" field.
func ExitIPLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExitIP, v))
}

// ExitIPLTE applies the LTE predicate on the "exit_ip" field.
func ExitIPLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExitIP, v))
}

// ExitIPContains applies the Contains predicate on the "exit_ip" field.
func ExitIPContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldExitIP, v))
}

// ExitIPHasPrefix applies the HasPrefix predicate on the "exit_ip" field.
func ExitIPHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldExitIP, v))
}

// ExitIPHasSuffix applies the HasSuffix predicate on the "exit_ip" field.
func ExitIPHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldExitIP, v))
}

// ExitIPIsNil applies the IsNil predicate on the "exit_ip" field.
func ExitIPIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExitIP))
}

// ExitIPNotNil applies the NotNil predicate on the "exit_ip" field.
func ExitIPNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExitIP))
}

// ExitIPEqualFold applies the EqualFold predicate on the "exit_ip" field.
func ExitIPEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldExitIP, v))
}

// ExitIPContainsFold applies the ContainsFold predicate on the "exit_ip" field.
func ExitIPContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldExitIP, v))
}

// ExitIPCheckedAtEQ applies the EQ predicate on the "exit_ip_checked_at" field.
func ExitIPCheckedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitIPCheckedAt, v))
}

// ExitIPCheckedAtNEQ applies the NEQ predicate on the "exit_ip_checked_at" field.
func ExitIPCheckedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExitIPCheckedAt, v))
}

// ExitIPCheckedAtIn applies the In predicate on the "exit_ip_checked_at" field.
func ExitIPCheckedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExitIPCheckedAt, vs...))
}

// ExitIPCheckedAtNotIn applies the NotIn predicate on the "exit_ip_checked_at" field.
func ExitIPCheckedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExitIPCheckedAt, vs...))
}

// ExitIPCheckedAtGT applies the GT predicate on the "exit_ip_checked_at" field.
func ExitIPCheckedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExitIPCheckedAt, v))
}

// ExitIPCheckedAtGTE applies the GTE predicate on the "exit_ip_checked_at" field.
func ExitIPCheckedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExitIPCheckedAt, v))
}

// ExitIPCheckedAtLT applies the LT predicate on the "exit_ip_checked_at" field.
func ExitIPCheckedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExitIPCheckedAt, v))
}

// ExitIPCheckedAtLTE applies the LTE predicate on the "exit_ip_checked_at" field.
func ExitIPCheckedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExitIPCheckedAt, v))
}

// ExitIPCheckedAtIsNil applies the IsNil predicate on the "exit_ip_checked_at" field.
func ExitIPCheckedAtIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExitIPCheckedAt))
}

// ExitIPCheckedAtNotNil applies the NotNil predicate on the "exit_ip_checked_at" field.
func ExitIPCheckedAtNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExitIPCheckedAt))
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.Proxy {
	return predicate.Proxy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.Proxy {
	return predicate.Proxy(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.NotPredicates(p))
}
